export {NotFoundPage} from './NotFound';
export {MainPage} from './Main';
export {CartPage} from './Cart';
export {CategoriesPage} from './Categories';
export {ContactsPage} from './Contacts';
export {AboutUsPage} from './AboutUs';
export {ShippingPage} from './Shipping';
export {PaymentPage} from './Payment';
export {ProductPage} from './Product';
export {SubCategoriesPage} from './SubCategories';
export {ProductsPage} from './Products';
export { AdminMain } from './AdminMain';
export { AdminCategory } from './AdminCategory';
export { SubCategory } from './AdminSubCategory';
